set dhcp config only after the lease_acquired is set
Previously, there was a DHCP server where lease_acquired returned the empty list
of options, and then this lead Dhcp_wire.pkt_into_buf to raise an exception:
```
Fatal error: exception Invalid_argument(\"Invalid options\")
Raised at Stdlib.invalid_arg in file \"stdlib.ml\", line 30, characters 20-45
Called from Dhcp_wire.pkt_into_buf in file \"duniverse/charrua/lib/dhcp_wire.ml\", line 1441, characters 20-60
Called from Netif.write_pure in file \"duniverse/mirage-net-solo5/src/netif.ml\", line 154, characters 12-20
Called from Netif.write in file \"duniverse/mirage-net-solo5/src/netif.ml\", line 166, characters 36-61
Called from Dune__exe__Unikernel.Net.handle_dhcp.(fun) in file \"unikernel.ml\", line 555, characters 16-150
```

The fix here is to delay the setting of dhcp_config (which means the code path
where lease_acquired returns the empty list is not reachable). The
lease_acquired callback requires a TCP stack and DNS resolver to be present (for
obvious purposes, to include hosts there or communicate to an external DNS
server).