Add missing dependency metrics-lwt
previous error:

mirage-dnsvizor-unix-dev> File "unikernel.ml", line 1788, characters 4-29:
mirage-dnsvizor-unix-dev> 1788 |     Metrics_lwt.init_periodic (fun () -> Mirage_sleep.ns (Duration.of_sec 10));
mirage-dnsvizor-unix-dev>            ^^^^^^^^^^^^^^^^^^^^^^^^^
mirage-dnsvizor-unix-dev> Error: Unbound module Metrics_lwt